All configs for running with ntb pushing with all subsystems. added current config files for crt northwall and flat.

diff --git a/sbn-nd/DAQInterface/run b/sbn-nd/DAQInterface/run
--- a/sbn-nd/DAQInterface/run
+++ b/sbn-nd/DAQInterface/run
@@ -1,4 +1,20 @@
 #!/usr/bin/env bash
+#
+#=====================================================================================
+#Run with argument of which directory in configs you want to use. Defaults to standard
+#=====================================================================================
+CONFIGDIR="standard"
+if [ ! -z "$1" ]
+    then
+    CONFIGDIR=$1
+fi
+
+if [ ! -d "$THIS_SBN_DAQ_DAQINTERFACE_DIR/configs/$CONFIGDIR" ]; then #check that config directory actually exists
+    echo "ERROR: configs/$CONFIGDIR does not exist. Please use existing directory as an argument or use no arguments to default to configs/standard."
+    echo "Stopping run script before I do anything"
+    exit 1
+fi
+
 this_start=$(date +%s)
 
 function getStatus()
@@ -11,22 +27,18 @@ function getStatus()
 getStatus "nil"
 # [ $status == 'Existing'] && (kill_daqinterface_on_partition.sh 0; exit 0 )
 
-
+setdaqcomps.sh tpc01 ntb01 ptb01PULL spectdc pmt01 pmt02 pmt03 pmt04 pmt05 pmt05 pmt07 pmt08 crtNorthWallWestPULL crtNorthWallEastPULL crtflat3_southwestPULL crtflat3_eastPULL crtflat3_northPULL
 #setdaqcomps.sh crt01
 #setdaqcomps.sh crt01PULL pmtx03 
 #setdaqcomps.sh pmtx03
 #setdaqcomps.sh pmtx04
 #setdaqcomps.sh spectdc pmtx03
 #setdaqcomps.sh spectdc pmtx03 crt01PULL
-#setdaqcomps.sh pmtx03 crt2x2upstrPULL crt2x2dwnstrPULL ptb01PULL spectdc
-#setdaqcomps.sh pmtx03 crt2x2dwnstrPULL ptb01PULL spectdc
 #setdaqcomps.sh pmtx03 ptb01PULL spectdc
-#setdaqcomps.sh pmtx03 crt2x2upstrPULL crt2x2dwnstrPULL spectdc
-#setdaqcomps.sh pmtx03 crt2x2upstrPULL crt2x2dwnstrPULL ptb01PULL
 ##setdaqcomps.sh pmtx03 crt01PULL spectdc
 #setdaqcomps.sh pmtx03 crt01PULL spectdc ptb01PULL
+#setdaqcomps.sh pmt01PUSH ptb01PULL
 
-setdaqcomps.sh tpc01 ntb01
 
 send_transition.sh boot boot.txt
 getStatus "booting"
@@ -38,7 +50,8 @@ do
 done
 
 #send_transition.sh config $2
-send_transition.sh config standard
+#send_transition.sh config standard
+send_transition.sh config $CONFIGDIR
 
 getStatus "configuring"
 while [ "$status" != 'ready' ]
